impress-org/givewp-next-gen

- packages/form-builder/src/components/sidebar/primary.js
- packages/form-builder/src/components/sidebar/styles.scss
- packages/form-builder/src/components/sidebar/tab-panel.js
- packages/form-builder/src/hooks/useSelectedBlocks.js
Resolves #30
This PR forks the `TabPanel` component from `@wordpress/components` so that the selected tab can be changed from outside of the component. Specifically, this injects the return value of `useState` as a prop to replace the internal use of `useState`.
- Open the Form Builder
- The "Form" settings tab should be selected by default
- Click on a block in the BlockList
- The "Block" settings tab should now be selected
-   [x] Acceptance criteria satisfied and marked in related issue
> refactor: Block settings tab is now selected when a block is clicked

- src/NextGen/DonationForm/Blocks/DonationFormBlock/Block.php
- src/NextGen/DonationForm/Blocks/DonationFormBlock/app/form/Form.tsx
- src/NextGen/DonationForm/DataTransferObjects/DonateFormData.php
- src/NextGen/DonationForm/Routes/DonateRoute.php
This adds persistence support for the company field on the next-gen donation form.  Since there is currently no option to specify if the field is required right now in the form-builder, we'll assume it's optional until we add that functionality.
- The donation form
- Removed a couple unnecessary hidden fields as well
- Make sure GiveWP develop branch is up to date
- In next-gen run `npm run dev`
- Create a next-gen form with a company field
- Donate using that form and fill in company field
- Make sure that field is recorded within a donation record in the back-end
-   [x] [Self …
> Feature: add company field persistence to next-gen form

- packages/form-builder/src/App.scss
- packages/form-builder/src/blocks/elements/index.js
- packages/form-builder/src/blocks/elements/paragraph.tsx
- packages/form-builder/src/components/sidebar/panels/field-types-list.js
- packages/form-builder/src/index.js
- src/Framework/FieldsAPI/Paragraph.php
- src/NextGen/DonationForm/Blocks/DonationFormBlock/Block.php
- src/NextGen/DonationForm/Blocks/DonationFormBlock/app/templates/elements/Paragraph.tsx
- src/NextGen/DonationForm/Blocks/DonationFormBlock/app/templates/index.tsx
This adds a paragraph element to the Form Builder! It allows folks to add simple text anywhere in any form. I looked into text formatting, and even added support for the core bold, italics, and link formats, but we apparently will need to [register format types](https://webomnizz.com/gutenberg-editor-add-button-to-the-toolbar/) in our app to get those to work properly. The [core types](https://github.com/WordPress/gutenberg/blob/0638a8c52199381080abb809fd5ccd137db5bb45/packages/format-library/src/bold/index.js) look easily available. I think it's fine if we add those in a subsequent PR.
Didn't really change too much, just added the element.
Use the block (or a few) in the Form Builder and check it out!
-   [ ] Relevant …
> Feature: add paragraph element

- src/NextGen/DonationForm/Controllers/DonationFormViewController.php
While working on the design preview in the form builder, I discovered a script conflict being loaded from give core.  The real problem is that core scripts _were_ being loaded in the iframe (along with all kinds of other scripts from add-ons). The NextGen donation form has no business loading any other scripts than the ones it enqueues through our framework.  This PR rearranges our script loading process within the donation form to make the order and loading of scripts predictable and specific to our form.
The process was actually a lot simpler than I originally thought.  Instead of calling `wp_head()` and having to dequeue a bunch of stuff we can break out the printing into specific parts...
**This is the order of loading:**
1. Enqueue global styles from WP using …
> Refactor: donation form now only loads scripts and styles that it needs

- packages/form-builder/src/App.js
- packages/form-builder/src/containers/BlockEditorContainer.tsx
- packages/form-builder/src/containers/HeaderContainer.jsx
- packages/form-builder/src/settings/donation-goal/index.js
- packages/form-builder/src/settings/form-fields/index.js
- packages/form-builder/src/settings/form-title/index.js
- packages/form-builder/src/settings/offline-donation/index.js
- packages/form-builder/src/stores/form-settings/index.tsx
- packages/form-builder/src/stores/form-settings/reducer.ts
Resolves #17
As the form builder application continues to grow, it's necessary to think through our data flow as it relates to all the new features we plan on implementing.  This PR replaces the existing state management approach with a reducer powered approach. This will give us a lot more flexibility in the future along with performance benefits.
**Provider**
- FormSettingsProvider
This is our Form's new store/provider.  It uses the React hook useReducer to store and persist state under the hood.  In order to update the state a "dispatch" method will be provided from the reducer.   This provides a lot of flexibility and performance benefits.
**Hooks**
- useFormSettings: convenient way of retrieving all the settings from the store as readOnly
- useFormSettingsDispatch: convenient way of …
> Refactor: form builder settings are now setup as a store with reducer

- packages/form-builder/src/App.scss
- packages/form-builder/src/App.tsx
- packages/form-builder/src/common/storage/drivers/local.ts
- packages/form-builder/src/common/storage/interface.ts
- packages/form-builder/src/components/canvas/DesignPreview.tsx
- packages/form-builder/src/components/sidebar/primary.js
- packages/form-builder/src/containers/BlockEditorContainer.tsx
- packages/form-builder/src/settings/donation-goal/index.js
- packages/form-builder/src/settings/index.ts
- packages/form-builder/src/settings/template/index.tsx
- packages/form-builder/src/stores/form-settings/index.tsx
- src/FormBuilder/ViewModels/FormBuilderViewModel.php
- src/FormBuilder/resources/js/storage.js
- tests/Unit/ViewModels/FormBuilderViewModelTest.php
This PR adds a new `template` form setting with a corresponding `<SelectControl />` which switches the template used in the `<DesignPreview />` canvas.
NOTE: There are some styling issues with the `<select />` element that need to be addressed.
> Design Preview can now switch templates

- packages/form-builder/src/components/canvas/DesignPreview.tsx
- packages/form-builder/src/components/canvas/DesignPreviewLoading/index.scss
This PR improves the Design Preview by rendering the updated preview in the background and only updating the preview after the document is fully rendered.
> Refactor: Design Preview update is now rendered in the background

- src/FormBuilder/Controllers/FormBuilderResourceController.php
- src/FormBuilder/Routes/CreateFormRoute.php
- src/FormBuilder/ViewModels/FormBuilderViewModel.php
- src/NextGen/DonationForm/Actions/ConvertQueryDataToDonationForm.php
- src/NextGen/DonationForm/Actions/GenerateDonationFormPreviewRouteUrl.php
- src/NextGen/DonationForm/Controllers/DonationFormViewController.php
- src/NextGen/DonationForm/DataTransferObjects/DonationFormGoalData.php
- src/NextGen/DonationForm/DataTransferObjects/DonationFormPreviewRouteData.php
- src/NextGen/DonationForm/DataTransferObjects/DonationFormViewRouteData.php
- src/NextGen/DonationForm/Factories/DonationFormFactory.php
- src/NextGen/DonationForm/Models/DonationForm.php
- src/NextGen/DonationForm/Properties/FormSettings.php
- src/NextGen/DonationForm/Repositories/DonationFormRepository.php
- src/NextGen/DonationForm/Routes/DonationFormPreviewRoute.php
- src/NextGen/DonationForm/ServiceProvider.php
- src/NextGen/DonationForm/ValueObjects/GoalType.php
- src/NextGen/DonationForm/ViewModels/DonationFormViewModel.php
- tests/Feature/Controllers/FormBuilderResourceControllerTest.php
- tests/Unit/Actions/ConvertQueryDataToDonationFormTest.php
- tests/Unit/Actions/GenerateDonationFormPreviewRouteUrlTest.php
- tests/Unit/DataTransferObjects/DonationFormPreviewRouteDataTest.php
- tests/Unit/DataTransferObjects/DonationFormViewRouteDataTest.php
- tests/Unit/DonationForm/DataTransferObjects/DonationFormGoalDataTest.php
- tests/Unit/DonationForm/ViewModels/DonationFormViewModelTest.php
- tests/Unit/ViewModels/FormBuilderViewModelTest.php
This PR separates the donation form's preview route and render route.  Essentially this means the preview route will accept params that can override the form's rendering logic for previewing changes, while the render route is confined to _only_  what's stored in the database using donation form ID.
Along with the new route, the Donation Form's `settings` property was updated with a new `FormSettings` property.  Everywhere that property was previously being used as an array has now been updated to the new api.
The form builder preview route and form settings property.
N/A
Just make sure the preview, settings, and block rendering works as expected.  There should be no visual change or issues.
-   [x] Relevant `@unreleased` …
> Feature: add separate route for form preview and introduce `FormSettings` property

- .github/workflows/unit-tests.yml
- packages/form-builder/src/App.tsx
- packages/form-builder/src/settings/donation-goal/index.js
- packages/form-builder/src/types/formSettings.ts
This PR adds a `goalAchievedMessage` setting to the form builder as a Donation Goal setting.
- Enable Donation Goals
- Enable Auto-Close Form
- Update the Goal Achieved Message
> Feature: Add Goal Achieved Message setting

- packages/form-builder/CONTRIBUTING.md
- packages/form-builder/src/App.scss
- packages/form-builder/src/blocks/fields/amount/inspector/delete-button.js
- packages/form-builder/src/blocks/fields/amount/level-buttons.js
- packages/form-builder/src/blocks/fields/donation-summary.js
- packages/form-builder/src/blocks/fields/payment-gateways.js
- packages/form-builder/src/components/sidebar/panels/field-types-list.js
- packages/form-builder/src/components/sidebar/styles.scss
- packages/form-builder/src/feedback/index.tsx
- packages/form-builder/src/feedback/popup/Container.tsx
- packages/form-builder/src/settings/styles/index.tsx
- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_amount-field.scss
- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_gateways.scss
- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_goal.scss
- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_header.scss
- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_inputs.scss
- src/NextGen/DonationForm/FormDesigns/DeveloperFormDesign/css/_amount-field.scss
- src/NextGen/DonationForm/FormDesigns/DeveloperFormDesign/css/_gateways.scss
- src/NextGen/DonationForm/FormDesigns/DeveloperFormDesign/css/_goal.scss
- src/NextGen/DonationForm/FormDesigns/DeveloperFormDesign/css/_inputs.scss
- src/NextGen/DonationForm/ViewModels/DonationFormViewModel.php
This PR updates all GiveWP [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) to use the `--givewp` prefix for consistency with the CSS class name prefix.
```diff
-    --give-primary-200: #E6FFE6;
-    --give-primary-300: #C2F2C3;
-    --give-primary-400: #AAF2AC;
-    --give-primary-500: #68BF6B;
-    --give-primary-600: #15AE56;
-    --give-primary-700: #5BA65E;
-    --give-primary-800: #3F7341;
+   --givewp-primary-200: #E6FFE6;
+   --givewp-primary-300: #C2F2C3;
+   --givewp-primary-400: #AAF2AC;
+   --givewp-primary-500: #68BF6B;
+   --givewp-primary-600: #15AE56;
+   --givewp-primary-700: #5BA65E;
+   --givewp-primary-800: #3F7341;
```
> Refactor: Update CSS Custom Properties prefix to --givewp

- packages/form-builder/src/App.scss
This PR adds a top border to the `block-card` element, when the Block tab is selected, so that the border separator is consistent with the other tabs.
| Form Tab | Block Tab (before) | Block Tab (after) |
|---|---|---|
|![image](https://user-images.githubusercontent.com/10858303/209176384-518c516c-058c-407e-b586-93583cef548f.png)|![image](https://user-images.githubusercontent.com/10858303/209176445-530355c7-e14b-4fb9-b15d-5e2f8aa09b9e.png)|![image](https://user-images.githubusercontent.com/10858303/209176885-5934e86e-b785-4ac8-a2f4-17425e1d1b96.png)|
> Fix: Set consistent border below tab group

- packages/form-builder/src/App.scss
This PR removes the extra bottom margin from the section block when not selected. Previously, this bottom margin was added as a placeholder to prevent shifting when the section block was selected and the block appender was rendered in that space.
| Before | After |
| --- | --- |
| ![Screenshot from 2022-12-22 11-43-23](https://user-images.githubusercontent.com/10858303/209183858-363cd89d-8bc3-4037-980e-0183c352a65a.png) | ![Screenshot from 2022-12-22 11-44-17](https://user-images.githubusercontent.com/10858303/209183853-80ba38a3-ac79-41f2-bb65-72275a3a3bcd.png)  |
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203547864809100
> Refactor: Remove layout margin when not selected

- packages/form-builder/src/App.scss
- src/NextGen/CustomFields/Controllers/DonationDetailsController.php
- src/NextGen/CustomFields/Controllers/DonorDetailsController.php
- src/NextGen/CustomFields/ServiceProvider.php
- src/NextGen/CustomFields/Views/DonationDetailsView.php
- src/NextGen/CustomFields/Views/DonorDetailsView.php
- src/NextGen/DonationForm/Repositories/DonationFormRepository.php
- tests/Unit/CustomFields/Controllers/TestDonationDetailsController.php
- tests/Unit/CustomFields/Controllers/TestDonorDetailsController.php
- tests/Unit/CustomFields/Views/TestDonationDetailsView.php
- tests/Unit/CustomFields/Views/TestDonorDetailsView.php
- tests/Unit/DonationForm/Repositories/TestDonationFormRepository.php
When viewing donor & donation detail pages who are not associated with a Next Gen form, there are errors for missing data.  This PR updates the logic for displaying custom fields in the detail pages with a check to see if it's a legacy form first before proceeding.
I also wrote a unit test for all the different pieces, so there were some minor tweaks to the logic along the way to make things more testable.
The donor & donation detail pages
Before (Donation not using Next Gen Form):
After (Donation not using Next Gen Form):
Donation using Next Gen Form (Still works):
Before (Donor not using Next Gen Form):
After:
Make sure there are no errors on donor & donation detail pages who have not used next gen forms.
-   [x] Relevant …
> Fix: custom fields backwards compatability

- src/FormBuilder/FormBuilderRouteBuilder.php
- src/FormBuilder/Routes/CreateFormRoute.php
- src/FormBuilder/Routes/EditFormRoute.php
- src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
> "Visual Builder" in admin menu is changed to "Add Form" with beta badge
https://app.asana.com/0/1203495935004514/1203495935004520/f
This PR updates the menu title for adding a new form (beta) as well as the related page title and page slug.
- Menu Title is now `Add Next Gen Form (Beta)`.
- Page Title is now `Visual Donation Form Builder` (without the per-release version).
- Page/Menu/Route Slug is now `form-builder-next-gen`.
Hard coded relative URLs have been replaced with a URL Builder class.
`'edit.php?post_type=give_forms&page=campaign-builder&donationFormID=' . $post->ID`
is now
`FormBuilderRouteBuilder::makeEditFormRoute($post->ID)`
The only visible change should be the menu title. Otherwise, creating a new form and editing an existing form should have the same behavior.
> Refactor: Rename Form Builder menu title, page title, page slug

- src/NextGen/DonationForm/Actions/StoreBackwardsCompatibleFormMeta.php
- src/NextGen/DonationForm/ServiceProvider.php
- tests/Unit/DonationForm/Actions/StoreBackwardsCompatibleFormMetaTest.php
> Next Gen forms are fully compatible with new Form list table
https://app.asana.com/0/1203495935004514/1203495935004522/f
This PR stores backwards compatible form meta for:
- Price Options (`multi`) <sup>1,2</sup>
- Donation Levels
- Donation Goal (enabled)
- Donation Goal Format
- Donation Goal Amount
<sup>1</sup> This will be updated to support the Set Donation price option when that is added to the form builder.
<sup>2</sup> The meta key is temporarily hard-coded and should be replaced after https://github.com/impress-org/givewp/pull/6614 is merged.
- Update the donation levels and donation goal form settings.
> Fix: Store backwards compatible form meta

- src/NextGen/DonationForm/Actions/ConvertQueryDataToDonationForm.php
- src/NextGen/DonationForm/Repositories/DonationFormRepository.php
- src/NextGen/DonationForm/ValueObjects/DonationFormMetaKeys.php
- tests/Unit/Actions/ConvertQueryDataToDonationFormTest.php
- tests/Unit/ViewModels/FormBuilderViewModelTest.php
> Form Builder JSON is stored in meta
https://app.asana.com/0/1203461259668711/1203484321897874/f
This PR moves the fields blocks JSON to form meta (out of post content<sup>1</sup>).
<sup>1</sup> The `post_content` now stores an empty JSON object as a placeholder. This is important for identifying a form as "Next Gen", which is used in the Next Gen Form Block and when editing a form.
- Adds `\Give\NextGen\DonationForm\ValueObjects\DonationFormMetaKeys::FIELDS`.
- Updates `\Give\NextGen\DonationForm\Actions\ConvertQueryDataToDonationForm::__invoke`
- Updates `\Give\NextGen\DonationForm\Repositories\DonationFormRepository::insert`
- Updates `\Give\NextGen\DonationForm\Repositories\DonationFormRepository::update`
- Updates `\Give\NextGen\DonationForm\Repositories\DonationFormRepository::prepa …
> Refactor: Move fields blocks to form meta

- packages/form-builder/src/App.scss
- packages/form-builder/src/settings/design/index.tsx
This PR restores the default color options in the color dropdown. The default values were removed by Gutenberg to be more dynamic.
Also, this affixes the color dropdown to the popover slot so that it does not scroll with the form.
Run `npm run build:form-builder` and check that the color settings in Design Mode have default options to choose from. Also, the color picker should not scroll with the form, but rather scroll with the sidebar.
> Fix: Add back color setting defaults

- packages/form-builder/src/blocks/fields/field.js
- packages/form-builder/src/components/sidebar/primary.js
- src/NextGen/DonationForm/ViewModels/DonationFormViewModel.php
- src/NextGen/DonationForm/resources/styles/global.css
- Updates custom fields to have "Display in Receipt" checked by default.
- Enqueues a new global stylesheet so our custom css variables are elevated to the head tag, this will ensure proper cascading of our css variables downstream.
- Moves the receipt settings into the form settings tab
- Comments out unused form settings that are not implemented yet
- Custom field default settings
- Form rendering styles
**Default settings**
**Form settings tab**
**Global styles in head tag**
- run `npm run build` and make sure form builder and form look okay.
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] [Self …
> Refactor: update default field settings, enqueue global form styles, and update form settings tab

- src/NextGen/Gateways/Stripe/NextGenStripeGateway/NextGenStripeGateway.php
- src/NextGen/Gateways/Stripe/NextGenStripeGateway/NextGenStripeRepository.php
This PR fixes an issue with a donor making a donation through different stripe accounts.  In order to achieve this we needed to catch Stripe's `InvalidRequestException` exception when a customer is not found and then create a new customer.  This is actually how the logic works in legacy.  We also are checking if a customer has the is_deleted flag so we can re-create the customer.
**Note**
While this logic has been working for us for some time, I am seeing room for improvement.  
**Multiple Stipe account**
GiveWP has the ability to use different Stripe accounts.  From what I can tell, our donor meta does not account for this - meaning anytime a donor uses stripe for a donation, the customer ID for _that_ account is saved to their meta - overwriting the previous value.  We should really …
> Fix: Stripe gateway customer retrieval

- packages/form-builder/src/settings/receipt/index.tsx
- src/NextGen/DonationForm/Properties/FormSettings.php
- src/NextGen/Framework/TemplateTags/DonationTemplateTags.php
- tests/Unit/Framework/TemplateTags/Actions/TestTransformTemplateTags.php
- tests/Unit/Framework/TemplateTags/TestDonationTemplateTags.php
This simplifies the default confirmation receipt template tags to `first_name`, `last_name`, and `email`. These all comes from the donation model so whatever was entered into these fields at the time of donating will be used.  Since this is technically an un-authenticated url - we don't want to expose any actual donor information.
The confirmation receipt & settings.
- Create a next gen form (or modify the existing settings with these template tags)
- Make a donation and view the confirmation receipt
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-rev …
> Refactor: simplify default receipt template tags

- packages/form-builder/src/blocks.json
- packages/form-builder/src/blocks/fields/amount/inspector/index.tsx
- packages/form-builder/src/blocks/fields/amount/settings.tsx
This PR ensures a fallback value for the `setPrice` value when using a fixed donation.
- Set the Donation Option to a Fixed Donation.
- Delete the value of the Set Donation setting.
- The Set Donation should fallback to `100`.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203940464851369
> Fix: Add fallback value for setPrice when fixed

- packages/form-builder/src/containers/HeaderContainer.tsx
This PR updates the icon for the right sidebar toggle button to match the Block Editor.
| Form Builder Header |
| --- |
| ![image](https://user-images.githubusercontent.com/10858303/229140070-90d54c94-7ad1-4cd3-8515-63dab42add73.png) |
> Chore: Update sidebar button icon

- src/NextGen/Gateways/PayPal/PayPalStandardGateway/Actions/CancelPayPalStandardSubscription.php
- src/NextGen/Gateways/PayPal/PayPalStandardGateway/PayPalStandardGatewaySubscriptionModule.php
- src/NextGen/ServiceProvider.php
Related: https://github.com/impress-org/givewp/pull/6756, https://github.com/impress-org/give-recurring/pull/1174
This adds recurring support for PayPal Standard in Next Gen enabled forms by building a gateway subscription module.  Eventually this module will be moved into give-recurring and replace the legacy paypal standard recurring logic - but for now it lives here just for compatibility with Next Gen forms.
PayPal standard gateway
Using Webhooks (local tunnel)
- Setup & enable PayPal standard with test credentials
- Create a next gen form with recurring setup
- Donate using PayPal standard
- (If feeling adventurous you can setup webhooks through a local tunnel but would need to modify the `notify_url` param in paypal args)
-   [ ] Acceptance criteria satisfied and marked in related …
> Feature: add recurring support for PayPal Standard

- packages/form-builder/src/blocks/fields/text/Edit.tsx
- tests/Unit/ViewModels/FormBuilderViewModelTest.php
This PR updates the label for the "store as donor meta" setting for custom fields.
| Before | After |
| -- | --- |
| ![Screenshot 2023-03-31 at 16-08-42 Visual Donation Form Builder Beta ‹ WordPress — WordPress](https://user-images.githubusercontent.com/10858303/229220127-d804a795-1101-45d0-b17f-f80ed7860339.png)  | ![Screenshot 2023-03-31 at 16-09-05 Visual Donation Form Builder Beta ‹ WordPress — WordPress](https://user-images.githubusercontent.com/10858303/229220126-69dd398d-d327-478c-8b39-37eb100a400d.png) |
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203838689047115
> Refactor: Update store as donor meta setting

- src/NextGen/DonationForm/ViewModels/DonationConfirmationReceiptViewModel.php
- src/NextGen/DonationForm/ViewModels/DonationFormViewModel.php
- src/NextGen/DonationForm/resources/embed.ts
- src/NextGen/DonationForm/resources/styles/components/_receipt.scss
This resolves an issue when the donation form redirects inside the iframe, the height of the frame is not calculated correctly. 
To fix this I updated our embed implementation of iframeResizer to use the [heightCalculationMethod](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#heightcalculationmethod) of `'taggedElement'` which is defined here:
> **taggedElement** Finds the bottom of the lowest element with a data-iframe-height attribute
> _The taggedElement option provides much greater performance by limiting the number of elements that need their position checked._
When the donation form is inside an iframe, this affects the calculation of it's height.
N/A
Make a donation using a next gen form and make sure the confirmation page is an appropriate …
> Fix: height calculation when iframe resizes

- src/NextGen/DonationForm/resources/app/DonationFormApp.tsx
- src/NextGen/DonationForm/resources/receipt/DonationConfirmationReceiptApp.tsx
The donation form uses `@wordpress/element` and related packages for react to play nicely with other blocks. It appears newer versions of WordPress are using react 18 where the root rendering api is a little different.  WP [docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-element/) have a conditional to provide backwards compatibility so this PR updates our implementation to follow that approach.
>Note: createRoot was introduced with React 18, which is bundled with WordPress 6.2. Therefore it may be necessary to mount your component depending on which version of WordPress (and therefore React) you are currently using. This is possible by checking for an undefined import and falling back to the React 17 method of mounting an app using render.
The …
> Chore: update implementation of react render to support react 18 & WordPress 6.2

- src/NextGen/Gateways/PayPalCommerce/PayPalCommerceGateway.php
- src/NextGen/Gateways/PayPalCommerce/PayPalCommerceSubscriptionModule.php
- src/NextGen/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
- src/NextGen/ServiceProvider.php
This PR updates the recurring implementation of the PayPal Donations gateway (now that recurring support is available in the `develop` branch of next gen).
- PayPal Provider Script is now set to defer loading.
- Extracted a `<PaymentMethodsWrapper/>` component for observing form changes.
- Visually hide Hosted Fields when not supported (prevent re-mounting error).
- Smart Buttons now conditionally set `createOrder()` or `createSubscription()`.
[![image](https://user-images.githubusercontent.com/10858303/230190616-7c9bb15c-21f7-48ac-8d96-8c424800dbdb.png)](https://www.loom.com/share/cbe6915cd9c04a459367f5a890052d55)
Toggle between one-time/recurring donations.
The PayPal Donations gateway should not throw an error.
> Refactor: Update recurring support for PayPal Donations

- give-next-gen.php
- src/NextGen/Gateways/Stripe/LegacyStripeAdapter.php
- src/NextGen/Gateways/Stripe/NextGenStripeGateway/NextGenStripeGateway.php
- src/NextGen/Gateways/Stripe/NextGenStripeGateway/nextGenStripeGateway.tsx
- src/NextGen/ServiceProvider.php
Depends on (but not completely): https://github.com/impress-org/givewp/pull/6768
We discovered that (currently), one of the existing Stripe gateways must be enabled in order for the Stripe webhooks to run.  This adds our new Stripe gateway to that list using a new filter `give_stripe_supported_payment_methods`.
Also included is a direct call to the legacy class to include the necessary files if this filter is not being used.  It checks if the `Give_Stripe_Webhooks` exists and if the new Stripe gateway is enabled.  This will make this backwards compatible regardless of the filter.
- This will make our new `NextGenStripeGateway` not have to rely on a legacy Stripe gateway to be enabled for webhooks to work properly.
N/A
- Test the Stripe webhook with only the next gen gateway enabled.
-   [ …
> Feature: add backwards compatibility for legacy Stripe webhooks

- src/Addon/Activation.php
This prevents a fatal error on activation when GiveWP is not installed.
The activation hook.
Try activating this plugin without GiveWP.
> Fix: add check for isGiveActive in activation hook

- src/NextGen/Gateways/Stripe/LegacyStripeAdapter.php
As reported by @Benunc, the Next Gen feature plugin was causing a break in form styles for the (legacy) Multi-Part template. I narrowed down the issue to the Next Gen Test Gateway and the (legacy) Stripe front-end files, which are included for the webhook listeners.
The `loadLegacyStripeWebhooksAndFilters()` method was checking for the `NextGenTestGateway::class` to be "active", but should instead have been checking for the `NextGenStripeGateway::class` - a simple typo in the code and oversight during code review.
Additionally, there issue revealed a bug in the legacy Stripe code, in which a callback for the filter hook `give_form_html_tags` returned `false` if no Stripe gateways were active when the filter hook expects an array to always be returned.
| Broken | Fixed |
| --- | --- | …
> Fix: Correct reference to Stripe Next Gen gateway when loading legacy Stripe code

- packages/form-builder/src/settings/styles/index.tsx
This PR removes the top margin offset from the code editor in the Custom Styles modal so that the editor is no longer hidden by the header.
| After |
| --- |
|![image](https://user-images.githubusercontent.com/10858303/232127773-c14157e4-c73f-465b-b34e-7feed9dc081a.png)|
| Before |
| --- |
| ![image](https://user-images.githubusercontent.com/10858303/232130204-a41dcc9f-926d-4f7b-aebc-908d040f89e0.png) |
In the Design tab, under the Custom Styles section, open the custom styles modal.
> Fix: Move editor out from under header in the Custom Styles modal

- src/NextGen/DonationForm/Actions/ConvertDonationFormBlocksToFieldsApi.php
Resolves #168
This makes it possible to add an empty section to the form builder without any child blocks.
The form builder, adding an empty section and saving.
N/A
- Pull branch
- Try adding an empty section and saving the form.
-   [x] Relevant `@unreleased` tags included in DocBlocks
> Fix: ability to add empty section in form builder

- src/NextGen/DonationForm/resources/registrars/templates/elements/DonationSummary.tsx
- src/NextGen/Framework/Receipts/Actions/GenerateConfirmationPageReceipt.php
- tests/Unit/Framework/Receipts/TestGenerateConfirmationPageReceipt.php
Resolves #172
This updates the confirmation page to display the subscription amount label with the correct frequency & period settings.
The confirmation page.
**Confirmation Page:**
**Donation Summary**
- Setup a form with recurring every 2 months
- Make a donation/subscription using the form
- Make sure the donation summary looks right.
- Make sure the subscription amount looks right.
-   [x] Relevant `@unreleased` tags included in DocBlocks
> Fix: update subscription amount label in confirmation page & donation summary

- packages/form-builder/src/blocks/fields/amount/Edit.tsx
- packages/form-builder/src/blocks/fields/amount/inspector/index.tsx
- packages/form-builder/src/blocks/fields/payment-gateways/Edit.tsx
- packages/form-builder/src/common/getWindowData.ts
- packages/form-builder/src/types/gateways.ts
- src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
This PR adds a new notice, under the "Recurring Donations" settings of the Amount field block, that instructs the user to enable a gateways that supports recurring.
This updates the way that gateways data is aggregated in the form builder in order to account for non-enabled gateways.
Enable the Recurring add-on, but disable all Next Gen gateways that support recurring.
> Feature: Add notice for recurring gateways

- package-lock.json
- packages/form-builder/package.json
- packages/form-builder/src/App.scss
- packages/form-builder/src/blocks/fields/amount/inspector/add-button.tsx
- packages/form-builder/src/blocks/section/settings.tsx
- packages/form-builder/src/components/forks/BlockCard.tsx
- packages/form-builder/src/components/forks/BlockIcon.tsx
- packages/form-builder/src/components/forks/BlockTypesList.tsx
- packages/form-builder/src/components/sidebar/Primary/index.tsx
- packages/form-builder/src/components/sidebar/Secondary.tsx
- packages/form-builder/src/components/sidebar/panels/FieldTypesList.tsx
- packages/form-builder/src/components/sidebar/popout/index.tsx
- packages/form-builder/src/containers/BlockEditorContainer.tsx
- packages/form-builder/src/containers/HeaderContainer.tsx
- packages/form-builder/src/feedback/index.tsx
- packages/form-builder/src/hooks/useSelectedBlocks.js
- packages/form-builder/src/index.tsx
- packages/form-builder/src/settings/offline-donation/donation-instructions.js
- src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
- src/FormBuilder/ViewModels/FormBuilderViewModel.php
- webpack.config.js
This updates the form builder build process to use wp-scripts when loaded from the plugin.  This is necessary to offload dependency management to WordPress for use with custom external blocks.
The form builder will not use the WordPress installation to load dependencies / gutenberg scripts.  Some imports that were coming directly from a package that is not publicly exposed were relocated and/or forked.
The main noticeable difference here is the secondary sidebar / block inserter.  It was too much of a rabbit hole to fork the components we were using so it is now simplified with the `<Library />` component that WP core and the isolated editor are using.
- Pull branch and run `npm install && npm run build'
- Open or create a next gen form and use the builder
- Everything should work the …
> Refactor: form builder to use wp-scripts

- src/NextGen/DonationForm/FormDesigns/ClassicFormDesign/css/_sections.scss
- src/NextGen/DonationForm/resources/app/form/MultiStepForm/components/NextButton.tsx
- src/NextGen/DonationForm/resources/styles/_base-overrides.scss
- src/NextGen/DonationForm/resources/styles/base.scss
- src/NextGen/DonationForm/resources/styles/elements/_form.scss
- src/NextGen/DonationForm/resources/styles/elements/_groups.scss
- src/NextGen/DonationForm/resources/styles/elements/_sections.scss
This updates the base form design styles to utilize css grid with gap to account for spacing of custom fields.
This was most noticeable on multistep form with some fields using margin and others using gap.  So using grid by default gives even spacing between fields and allows custom form designs to further customize.
The base form design styles
**Before**
**After**
- Pull branch and run `npm run dev`
- Add some custom fields and switch between form designs
- Make sure the spacing looks acceptable.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-review …
> Refactor: update base styles to support custom fields

- src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
- tests/Unit/DonationForms/Actions/TestConvertDonationFormBlocksToFieldsApi.php
This adds a generic `givewp_donation_form_block_render` hook and also adds a missing parameter to the existing hook. The filter was previously passing the block as the first parameter, but this isn't correct. For a filter the first parameter isn't context but the value being filtered. This makes it problematic for multiple functions firing on the same hook, and makes it impossible to chain hooks — as is being done now with the addition of the new hook.
Related: https://github.com/impress-org/give-fee-recovery/pull/323
The `givewp_donation_form_block_render_{$blockName}` hook.
I believe the only plugin using this hook so far is Fee Recovery. So make sure that still works with the new PR.
-   [x] Relevant `@unreleased` tags …
> Refactor: add generic hook and additional parameter

- package-lock.json
- package.json
- src/FormBuilder/resources/js/form-builder/src/components/onboarding/steps/withText.tsx
This pull request fixes an issue where ReactDOMServer was not being compiled by wp-scripts. To convert a React component to a string, we replaced it with a simple solution. We create an element in memory, render the component into it, then use the element's innerHTML string.
`withText.tsx`, used on Onboarding
> Refactor: replace ReactDOMServer function with temporary rendering

- src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx
This add a "smart default" to the donation amount levels setting by double the previous amount.
The donation amount block levels setting
- build assets, go into a form and click "Add another level" on the donation amount levels.
- the next value should be double the amount of the previous level
- 
> Feature: calculate the default value of next donation amount level

- src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php
- src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx
- tests/Feature/Gateways/Stripe/TestStripePaymentElementGateway.php
- tests/Feature/Gateways/Stripe/TestStripePaymentElementGatewaySubscriptionModule.php
Resolves: https://feedback.givewp.com/next-gen/p/error-occurs-when-using-ideal-or-bancontact-with-new-stripe-gateway
Some payment methods add their own additional name and email fields.  These are redundant after the donor has already filled them out on the GiveWP form so we can omit them and provide the field data from the form submission. 
Stripe payment methods that add their own name and email fields.
**Before**
**After**
- test out using Ideal and Bancontact
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …
> Refactor: omit stripe name and email fields

- src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx
This fix ensures the recurring period options are in the appropriate order (time-frame ascending) - regardless of the time/order in which you toggle them.
The recurring billing period options
Toggle the recurring billing periods in different orders and make sure they are in ascending order (in terms of time frame)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204414138863604
> Fix: order recurring options before updating

- src/FormBuilder/resources/js/form-builder/src/blocks.json
- src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/Edit.tsx
- src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx
This resolves an issue that was breaking the donation amount block when interacting with the fixed donation amount setting.
The donation amount block.
N/A
- Build assets
- Update donation amount block setting to be _fixed donation_ and interact with the amount field. it should not break the block.
> Fix: prevent fixed donation amount settings breaking block

- src/DonationForms/resources/registrars/templates/fields/Amount/index.tsx
This fixes an issue when Donation Amount Levels were not working when the Custom Amount field was disabled.
The donation amount field on the donation form
N/A
- Disable custom amount & publish.
- View the form and make sure you can click on the donation levels
> Fix: prevent conflict between custom amount field and donation levels

- src/DonationForms/ServiceProvider.php
- src/DonationForms/Shortcodes/GiveFormShortcode.php
Depends on https://github.com/impress-org/givewp/pull/6849
This pull request adds support to render v3 forms on the `give_form` shortcode hooking onto the recently added `givewp_form_shortcode_output` filter.
`give_form` shortcode and the legacy Donation Form block as it uses the same shortcode to render the form.
Add a legacy Donation Form block to a post/page, select a v3 donation form. The form must be rendered as expected.
-   [x] Relevant `@unreleased` tags included in DocBlocks
---
- To see the specific tasks …
> Feature: support v3 forms on give_form shortcode

- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/FieldSettingsHOC.tsx
- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/index.tsx
- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/normalizeFieldSettings.ts
- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/slots.ts
- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/types.ts
- src/FormBuilder/resources/js/form-builder/src/supports/field-settings/updateBlockTypes.ts
This pull request adds a new slot, `<AdvancedSettingsSlot>`, to the Field Settings HOC. Add-ons can use this slot to add their own custom settings to the _Advanced_ section in the Inspector.
Directly using the `<InspectorAdvancedConstrols>` slot causes a rendering conflict with the fields added by the HOC.
Example of usage:
> Feature: add AdvancedSettingsSlot to HOC

- src/DonationForms/resources/registrars/templates/groups/DonationAmount/DonationAmountCurrencySwitcherMessage.tsx
- src/DonationForms/resources/types.ts
- src/Framework/FieldsAPI/Properties/DonationForm/CurrencySwitcherSetting.php
This adds support for exchange rate fraction digits to display the donor.
Note: this will only affect the message displayed to the donor, not the actual donation amount.  Learn more [here](https://givewp.com/documentation/add-ons/currency-switcher/)
Adds new exchange rate fraction digit property to the CurrencySwitcherSetting
Programatically:
```
use Give\Framework\FieldsAPI\DonationForm;
use Give\Framework\FieldsAPI\Properties\DonationForm\CurrencySwitcherSetting;
add_action('givewp_donation_form_schema', static function (DonationForm $form) {
$currencySwitcherSettings = [
new CurrencySwitcherSetting('USD', 0, ['test-gateway', 'stripe_payment_element']),
new CurrencySwitcherSetting('EUR', 0.911699, ['test-gateway', 'stripe_payment_element'], 6),
]; …
```
> Feature: add currency setting exchange rate fraction digits

- src/FormBuilder/resources/js/form-builder/src/settings/email/logo-upload/index.tsx
- src/FormBuilder/resources/js/form-builder/src/settings/email/template-options/index.tsx
- src/FormBuilder/resources/js/form-builder/src/styles/_email-settings.scss
- src/FormBuilder/resources/js/form-builder/src/styles/_form-builder.scss
This PR address some really small CSS issues around the Email Notifications settings in the Form Builder.
- Modal scrollbars
- Text alignment on modal tabs
- Margins of the Logo URL field
Before:
After:
-   [x] Reviewed by the designer (if follows a design)
> Fix: css small issues

- src/FormBuilder/resources/js/form-builder/src/styles/_form-builder.scss
Resolves #219
This PR resolves the issue where NextGen editor styles were altering the visual appearance of the radio and checkbox components inside InspectorControls -> PanelBody. 
Radio and Checkbox component visual appearance 
-   [x] Acceptance criteria satisfied and marked in related issue
> NextGen editor styles no longer affect the visual appearance of radio and checkbox components

- src/DonationForms/Properties/FormSettings.php
- src/FormBuilder/Actions/UpdateFormGridMeta.php
- src/FormBuilder/ServiceProvider.php
- src/FormBuilder/resources/js/form-builder/src/components/sidebar/Primary/index.tsx
- src/FormBuilder/resources/js/form-builder/src/settings/form-grid/index.tsx
- src/FormBuilder/resources/js/form-builder/src/settings/index.ts
- src/FormBuilder/resources/js/form-builder/src/types/formSettings.ts
- src/FormMigration/Steps/FormGrid.php
This PR adds the Form Grid settings to the Visual Donation Form Builder.
Toggle the form grid settings to be customized and add a redirect URL and a donate button text.
> Feature: Add form grid settings to builder

- src/FormBuilder/resources/js/form-builder/src/styles/_email-settings.scss
A style applied to the wp-uploader ```[id^='__wp-uploader'] {
z-index: 9999999999;
}``` is being inherited by the media-frame class which covers the entire frame. 
I applied a z-index to the media frame to allow the button to be clicked again.
Email Media Frame
https://github.com/impress-org/givewp-next-gen/assets/75056371/7db29f1b-b192-4de9-9217-e4d16fa77ad0
- Under Form settings select Email settings.
- Select add or upload file.
- Close the but media frame with the close button on the top right.
- 
- ## Pre-review Checklist
-   [ ] [Self …
> Fix: Adjust media frame index to allow media-close-button to be clicked

- src/DonationForms/Properties/FormSettings.php
- src/FormBuilder/resources/js/form-builder/src/components/sidebar/Primary/index.tsx
- src/FormBuilder/resources/js/form-builder/src/settings/offline-donation/donation-instructions.js
- src/FormBuilder/resources/js/form-builder/src/settings/offline-donation/index.js
- src/FormBuilder/resources/js/form-builder/src/types/formSettings.ts
- src/FormMigration/FormMetaDecorator.php
- src/FormMigration/Steps/OfflineDonations.php
This PR re-introduces the Offline Donation settings in the Visual Form Builder, which includes the Donation Instructions text editor.
- Create (or migrate) a v3 donation form
- Enable customized offline donation settings
- Edit the offline donation instructions setting
> Feature: Offline Donation Instruction settings

- src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss
Resolves #230
This PR resolves the issue where NextGen editor styles were altering the visual appearance of the radio and checkbox components inside the block editor
Radio and Checkbox component visual appearance inside the block editor
-   [x] Acceptance criteria satisfied and marked in related issue
> Editor styles no longer affect the visual appearance of radio and checkbox components inside the block editor

- package-lock.json
- package.json
- src/FormBuilder/resources/js/form-builder/src/common/parseMissingBlocks.ts
- src/FormBuilder/resources/js/form-builder/src/common/registerBlocks.ts
- src/FormBuilder/resources/js/form-builder/src/common/revertMissingBlocks.ts
- src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorContainer.tsx
- src/FormBuilder/resources/js/form-builder/src/containers/HeaderContainer.tsx
This implements the missing block when a previously registered block is not available.
The way this works is that when a block is missing, we replace it with the missing blockType and store the original block type json from the database in the missing blockType's originalContent attribute.
Then, when the block is found again as a registered block, we replace the missing block with the stored originalContent attribute.
Note: this is currently pulling in the WordPress core missing blockType to achieve this.  After going through this, I think it might be better to supply our own version to prevent any conflicts in future WP versions.
- The form builder and how it handles missing blocks
- Install a block extension like fee recovery
- Create a v3 form, add the fee recovery block and save.
- …
> Feature: Add missing block implementation

- src/DonationForms/Models/DonationForm.php
- src/DonationForms/Repositories/DonationFormRepository.php
- src/FormBuilder/Controllers/FormBuilderResourceController.php
Depends on: https://github.com/impress-org/givewp/pull/6864
This catches a NameCollisionException from the form schema and responds to the client with a valuable message.
The form builder update processing.
Make sure GiveWP is `>=` https://github.com/impress-org/givewp/pull/6864
Try updating a custom field name with a reserved or existing programmatic name.  You should see an exception message.
> Feature: throw name collision exception during form builder update
